module.exports = {
  estoque: require('./estoque/estoque.marko'),
  analiseEstoque: require('./estoque/analiseEstoque.marko'),
  paginadoconselheiro: require('./conselheiros/paginadoconselheiro.marko'),
  solicitacoescons: require('./conselheiros/solicitacoescons.marko'),
  carregacsv: require('./carregacsv/carregacsv.marko'),
  escolhecsv: require('./escolhecsv/escolhecsv.marko'),
  escolhecsvregap: require('./escolhecsv/escolhecsvregap.marko'),
  escolhecsvanaliseestoque: require('./escolhecsv/escolhecsvanaliseestoque.marko'),
  escolhecsvreinp: require('./escolhecsv/escolhecsvreinp.marko'),
  reinpgeral: require('./reinp/reinpgeral.marko'),
  detalhareinp: require('./reinp/detalhareinp.marko'),
  corrigeReinp: require('./reinp/corrigereinp.marko'),
  regapCojul: require('./regap/regapCojul.marko'),
  regap: require('./regap/regap.marko'),
  faqdipaj: require('./faqdipaj/faqdipaj.marko'),
  cadastrafaqdipaj: require('./faqdipaj/cadastrafaqdipaj.marko'),
  formFAQ: require('./faqdipaj/formFAQ.marko'),
  calendario: require('./calendario/calendario.marko'),
  calendarioView: require('./calendario/calendarioView.marko'),
  gestaoconhecimento: require('./gestaoconhecimento/gestaoconhecimento.marko'),
  gestaoGC: require('./gestaoconhecimento/gestaoGC.marko'),
  gestaoPortal: require('./portalcojul/gestaoPortal.marko'),
  portalCojul: require('./portalcojul/portalCojul.marko'),
  gestaosolicitacoes: require('./gestaosolicitacoes/gestaosolicitacoes.marko'),
};
